### ISSUE TITLE
device.py

### ISSUE THREAD

**Issue by P3nguin-M** [alephsecurity/abootool#10]
Have all dependencies installed. Can load a factory image with .adbtool.py -a "path/to/fw.zip"
Afterwards, using "-l" shows:
INFO: Welcome to abootool by Aleph Research, HCL technologies
INFO: BY OEM:
INFO: -------
INFO:          motorola:   2
INFO: 
INFO: BY DEVICE:
INFO: ----------
INFO:             SHAMU:   1               harpia:   1

Now, when I run ./abootool.py alone after loading firmware, i get:

INFO: Welcome to abootool by Aleph Research, HCL technologies
INFO: fastboot connected to ZX1G22K2HQ
Traceback (most recent call last):
  File "./abootool.py", line 95, in <module>
    sys.exit(main())
  File "./abootool.py", line 73, in main
    name = dev.device()
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 271, in device
    return Config.bootloader_names[self.bootloader_name()]
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 259, in bootloader_name
    p = self.product()
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 247, in product
    return self.getvar("product")
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 240, in getvar
    self.data[k] = self.wait_for_fb_command("Getvar", False, False, k)
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 188, in wait_for_fb_command
    self.resolve_fb_error()
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 303, in resolve_fb_error
    self.fb_error = self.do_fb_command("Oem", True, Config.oem_error_cmd)
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 157, in do_fb_command
    getattr(self.fastboot(), func)(info_cb=self.last_output, *args, **kargs)
  File "/media/kevin/Projects/LG Stuff/abootool/device.py", line 139, in fastboot
    return fastboot.FastbootCommands(self.usbdev)
TypeError: __init__() takes exactly 1 argument (2 given)
 
Have looked through the code, but cannot figure out what's failling.. __init__ in device.py??

**Comment by bene2929** [comment]
Same here

**Comment by naveensingh** [comment]
anyone figured it out yet?
Edit:
Fixed it.
Do this:
pip install adb==1.2.0

Latest version fastboot 1.3.0 is throwing errors.
