### ISSUE TITLE
TypeError: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by YamilMarques** [alephsecurity/abootool#14]
Hello,

I managed to install all the dependencies and setup the environment to make it work the solution but I'm getting an error in the script after detecting the device in fastboot:

`./abootool.py 
INFO: Welcome to abootool by Aleph Research, HCL technologies
INFO: Waiting for device...
INFO: fastboot connected to 1PASH9AYPU9241
Traceback (most recent call last):
  File "./abootool.py", line 95, in <module>
    sys.exit(main())
  File "./abootool.py", line 73, in main
    name = dev.device()
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 271, in device
    return Config.bootloader_names[self.bootloader_name()]
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 259, in bootloader_name
    p = self.product()
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 247, in product
    return self.getvar("product")
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 240, in getvar
    self.data[k] = self.wait_for_fb_command("Getvar", False, False, k)
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 188, in wait_for_fb_command
    self.resolve_fb_error()
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 303, in resolve_fb_error
    self.fb_error = self.do_fb_command("Oem", True, Config.oem_error_cmd)
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 157, in do_fb_command
    getattr(self.fastboot(), func)(info_cb=self.last_output, *args, **kargs)
  File "/Users/ymarquesdemello/Desktop/testingOEM/abootool/device.py", line 139, in fastboot
    return fastboot.FastbootCommands(self.usbdev)
TypeError: __init__() takes exactly 1 argument (2 given)`

I'm running Python 2.7.16.

Is anyone else experience this issue as well?

**Comment by YamilMarques** [comment]
Edit: Fixed it.
For anyone who can experience the same issue, make sure to install the adb version 1.2.0. I was getting issues with a more modern version.

"pip install adb==1.2.0"
