### ISSUE TITLE
ADB ERROR

### ISSUE THREAD

**Issue by trounce1** [alephsecurity/abootool#7]
./abootool.py -h
Traceback (most recent call last):
  File "./abootool.py", line 7, in <module>
    import device
  File "/Users/harry/Downloads/abootool-master/device.py", line 8, in <module>
    from adb import fastboot,common,usb_exceptions,adb_commands, sign_m2crypto
ImportError: No module named adb

What am i missing here?

not sure what is wrong???

any help will be apreciated

**Comment by Ante0** [comment]
You need to 'pip install adb'.

**Comment by tanmay380** [comment]
i'm getting a hell lot of error installing this adb
![Screenshot (206)](https://user-images.githubusercontent.com/38492979/84595943-71656380-ae78-11ea-817c-1b0981bd5f45.png)
![Screenshot (207)](https://user-images.githubusercontent.com/38492979/84595945-732f2700-ae78-11ea-85c7-5b5f3ad0bd47.png)

**Comment by karmaadhin** [comment]
I'm facing the same issue(red errors) .. any solution yet ?

**Comment by vpolinov** [comment]
Same issue here.  Same stupid diagnostics re "no module named adb"

I see, **alephsecurity** does not care about his buggy piece of ....

**Comment by ghost** [comment]
sudo apt-get install libssl-dev swig python3-dev gcc
Fixed installation of ADB.
